# $OpenBSD: Makefile.template,v 1.71 2014/07/10 12:33:17 sthen Exp $

COMMENT =		???

V =			2.0.0
DISTNAME =		chocolate-doom-${V}

CATEGORIES =		games

HOMEPAGE =		http://www.chocolate-doom.org/

MAINTAINER =    James Lecocq <jlq@tmp.li>

PERMIT_PACKAGE_CDROM=Yes

MASTER_SITES =		http://www.chocolate-doom.org/downloads/${V}/

USE_GMAKE =		Yes
CONFIGURE_STYLE=        gnu


.include <bsd.port.mk>
