# $OpenBSD: Makefile.template,v 1.71 2014/07/10 12:33:17 sthen Exp $

COMMENT =		gbc emulator for linux written in C using the SDL

V =			20060309
DISTNAME =		gngb-${V}

CATEGORIES =		games

HOMEPAGE =		http://m.peponas.free.fr/gngb/

MASTER_SITES =		http://m.peponas.free.fr/gngb/download/

USE_GMAKE =		Yes
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
